### PR TITLE
Update agenttesla.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Please, be careful with agenttesla IOCs as those are in almost all cases just compromised domains. Also, I've opened 3 random domains from here and all were old and compromised

**Comment by MikhailKasimov** [comment]
Ok, will re-check domains a little bit later.

**Comment by MikhailKasimov** [comment]
Have cleaned the list.

**Comment by stamparm** [comment]
Sorry, have to drop this one down. Tried again 3 random domains, all older than couple of years. I've said my opinion of AgentTesla in previous comment

**Pull request closed without merging**
