### PR TITLE
Create elf_sshbruteforce.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://www.virustotal.com/#/ip-address/185.10.68.163

### CODE REVIEW

**Comment by stamparm** [comment]
This is some generic ELF malware.

**Comment by MikhailKasimov** [comment]
Yes, but they are from

```
185.10.68.163/miner.sh
185.10.68.163/scanner.sh
185.10.68.163/worlswest.sh
185.10.68.163/tcpconnect_zmap_386 (403)
185.10.68.163/tcpconnect_zmap_arm
185.10.68.163/bruteforce_ssh_386 (403)
185.10.68.163/bruteforce_ssh_arm
185.10.68.163/bruteforce_ssh
```

```Rabbit``` name is given by Dr.Web. It is not our blame, that other so-called ```anti-viruses``` do not detect this malware.

But because this malware can be downloaded, MT should detect it.

**Comment by stamparm** [comment]
So, you can contact 185.10.68.163? I am not able to reach it on port 80

**Comment by MikhailKasimov** [comment]
Unfortunately yes, just right now this IP is off. On last Friday I downloaded these files successfully and they were added as ```Linux.Rabbit``` by Dr.Web.

**Comment by MikhailKasimov** [comment]
@stamparm https://twitter.com/luc4m/status/1044148790008205312

**Comment by MikhailKasimov** [comment]
we can create ```malicious_elf.txt``` so such generic unnamed ELF-malware.

**Comment by MikhailKasimov** [comment]
Have rescan one of ```Rabbit```: https://www.virustotal.com/#/file/6570e9d347e6cb0b4472f647481887a9e91930774c00f3025307079be21a9344/detection

Choose any name you wish. :)

And do not forget to visit ```Relations``` tab to make yourself sure I was right on IP: https://www.virustotal.com/#/file/6570e9d347e6cb0b4472f647481887a9e91930774c00f3025307079be21a9344/relations

**Comment by stamparm** [comment]
1) This one is just a proof that IPs are lousy trails for malware. If that IP is down, something like `185.10.68.163/scanner.sh` will never be triggered
2) `malware/elf_generic.txt` can be used

**Comment by MikhailKasimov** [comment]
1. Yes, but generic ```/scanner.sh``` will triggered any, what live is.

2. OK.

**Pull request merged**
