### PR TITLE
Update android_roamingmantis.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Generalization for ```bb-```, ```bt-```, ```dd-``` and ```dj-``` prefixes, which were met before. If all ```aa-aa.top - zz-zz.top``` is needed, please, let me know. Entire ```aa-aa.top - zz-zz.top``` file is 4,8 Mb.

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
@stamparm Please, merge this for this moment due to things like this:

https://twitter.com/NaomiSuzuki_/status/1148141639992373248
https://twitter.com/NaomiSuzuki_/status/1148141642769002501

They are met every day (2-3 new domains), and this is rather hard to monitor it.

Later, this all will be optimized after ```I'll do some support for regexes``` (c) https://github.com/stamparm/maltrail/pull/2655#issuecomment-509004419

Thank you!

**Comment by MikhailKasimov** [comment]
New: https://twitter.com/NaomiSuzuki_/status/1148165815931289601

**Comment by stamparm** [comment]
Implemented support for regexes with #1467 (please use it wisely - use it ONLY if absolutely needed)

**Comment by MikhailKasimov** [comment]
> 
> 
> Implemented support for regexes with #1467 (please use it wisely - use it ONLY if absolutely needed)

Yes, sure.

**Comment by MikhailKasimov** [comment]
@stamparm ```\b[a-z]{2}-[a-z]{2}.top``` for trails ```aa-aa.top``` (have checked this via https://regex101.com/) and ```jppost-[a-z]{2,3}.(com|top)```.

The question is -- does MT support things like ```\b```, ```\w``` etc for such cases?

**Comment by stamparm** [comment]
@MikhailKasimov please prefer ranges (e.g. [a-z]) instead of shortcuts (e.g. `\w`). Maltrail recognizes regexes by those ranges. Nevertheless, stuff like `\b` should be ok (as long as there are ranges inside)

**Comment by stamparm** [comment]
p.s. `\b[a-z]{2}-[a-z]{2}.top` should work (tested this moment)

**Comment by MikhailKasimov** [comment]
> 
> 
> @MikhailKasimov please prefer ranges (e.g. [a-z]) instead of shortcuts (e.g. `\w`). Maltrail recognizes regexes by those ranges. 

```\w``` was displayed as demo. Of course, I will use [a-z].

>Nevertheless, stuff like `\b` should be ok (as long as there are ranges inside)

O! This is pretty fine. Because I want to avoid situations like this (see screen -- this is without ```\b```)

without_b

**Comment by MikhailKasimov** [comment]
@stamparm Later, in the evening of today, I will proceed all this stuff.

**Comment by MikhailKasimov** [comment]
@stamparm Can be merged now (I hope).

**Comment by stamparm** [comment]
Can't accept `\b[a-z]{2}\-[a-z]{2}\.[a-z]{2,3}` because of the following (p.s. neither in case of putting a boundary mark at the end):


dddd

**Comment by MikhailKasimov** [comment]
@stamparm Try again with https://github.com/stamparm/maltrail/pull/2648/commits/96e97129d8a31aaff355347344895061b533dccf

**Comment by stamparm** [comment]
I explicitly said **p.s. neither in case of putting a boundary mark at the end**. That actually means that not any form of that same regex can go in. It will mark 1 percent of Alexa1m as `roamingmantis`

**Comment by MikhailKasimov** [comment]
And again: https://github.com/stamparm/maltrail/pull/2648/commits/316c8622f1289168744051039ea3edc22bad894c

**Comment by MikhailKasimov** [comment]
> 
> 
> I explicitly said **p.s. neither in case of putting a boundary mark at the end**. That actually means that not any form of that same regex can go in. It will mark 1 percent of Alexa1m as `roamingmantis`

I have noted ```p.s.``` only after adding. Changed to explicit domains (com, cn, top). Try with this.

**Comment by stamparm** [comment]
None version of that same regex can go in. Neither with `com`:

```
$ cat alexa1m.txt | grep -E "\b[a-z]{2}\-[a-z]{2}\.com\b"
ah-me.com
mm-cg.com
in-en.com
rd-fs.com
rr-sc.com
sa-mp.com
db-ip.com
pv-ip.com
ff-gh.com
gw-ec.com
cy-pr.com
ru-mi.com
ir-dl.com
hp-ez.com
in-ku.com
se-ed.com
fx-on.com
on-ze.com
fs-uk.com
za-sh.com
inches-to-cm.com
na-kd.com
ln-cc.com
qq-ex.com
lm-us.com
kc-mm.com
ex-fs.com
ls-rp.com
sj-tl.com
us-ex.com
xs-kw.com
bosch-do-it.com
modeles-de-cv.com
hide-my-ip.com
...
```

**Pull request merged**
