### PR TITLE
Create thbaiai_banker.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
C2 addresses. Domain list is in #862

### CODE REVIEW

**Comment by stamparm** [comment]
Why #862 and #863 in different files?

**Comment by stamparm** [comment]
p.s. I would just leave `generic.txt` as that same domain is/will die (hence, no HTTP requests toward it)

**Comment by MikhailKasimov** [comment]
> 
> 
> Why #862 and #863 in different files?

Because domain ```lt99.ddns.net``` and  ```/al/index.php```/```logsD/index.php``` trails, when separate, seem to be "too generic" (c). Hence, I decided to put full trail paths as the explicitly defined trail for this banker-trojan.

**Comment by stamparm** [comment]
Domain is dead (as said before), hence there will be no HTTP requests. `generic` has been already merged

**Pull request closed without merging**
