### PR TITLE
Update asyncrat.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Not sure what's the reasoning nor source of all those IP:ports

**Comment by MikhailKasimov** [comment]
To cover all IPs for respective ```*.ngrok[.]io``` from https://twitter.com/c3rb3ru5d3d53c/status/1399327839896342529

**Comment by stamparm** [comment]
you know my stance on cluster bombing

**Comment by MikhailKasimov** [comment]
Fixed

**Pull request merged**
