### PR TITLE
Create carrotbat.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
-> `apt_unknown.txt`

**Comment by MikhailKasimov** [comment]
Hmmm... even if malware name is given explicitly in initial article?

**Comment by stamparm** [comment]
We had a similar discussion couple of days ago [here](https://github.com/stamparm/maltrail/pull/839#issuecomment-469626741).

Even `carrotbat` is better than `apt_carrotbat` if you insist on having a name. I just wanted to mark it as `apt_` as it has an `APT` actor behind it.

**Comment by MikhailKasimov** [comment]
#861

**Pull request closed without merging**
