### PR TITLE
Update ua.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
I've skipped for example `python` (default UA for python) because there are far too many appliance agents that use python for regular activities. I could merge this one, but I am afraid that there will be FP recognitions here (too)

**Comment by MikhailKasimov** [comment]
Can you take some experiments on your side, plz? Or, if it is really risky to catch ton of FPs, no problem not to apply this trail.

**Comment by stamparm** [comment]
I'll merge it and check the status in couple of days

**Comment by MikhailKasimov** [comment]
OK, thnx!

**Pull request merged**
