### PR TITLE
Update stealer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Some subdomains were used here, but the whole domain is used by other entities too. Please Google

**Comment by MikhailKasimov** [comment]
Hm  due to http://www.malwaredomainlist.com/mdl.php?inactive=on&sort=Reverse&search=&colsearch=All&ascordesc=ASC&quantity=100&page=886 this domain can be placed to ``domain.txt```. Applicable?

**Comment by stamparm** [comment]
Yup

**Comment by MikhailKasimov** [comment]
Fixed via https://github.com/stamparm/maltrail/pull/4022/commits/aaa0bc709b84339f7018b940e3cfd7687759cf94

**Pull request closed without merging**
