### PR TITLE
Create phrasing.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
I can't seem to find any info on this "phrasing". It looks like generic term

**Comment by stamparm** [comment]
-> `generic.txt`

p.s. can't go to andromeda based on one AV provider

**Comment by MikhailKasimov** [comment]
OK

**Comment by stamparm** [comment]
This one is still pointing to `phrasing.txt`

**Comment by MikhailKasimov** [comment]
Yes, I know. Gonna parse its samples on Sat or Sun.

**Comment by MikhailKasimov** [comment]
Due to https://www.virustotal.com/gui/file/8b7539df3ca2a8d75f9ce1da69b66b761ff1661fe42b03f18103cd0b0f068956/detection I have resounded this in ```nitol```:  https://github.com/stamparm/maltrail/pull/9182/commits/cc8de437f54cd18124fa649e47e3f2eab85f6fb9

**Pull request closed without merging**
