### PR TITLE
Create neutrino.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://twitter.com/ViriBack/status/1031244776023056384

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
@stamparm  Due to https://twitter.com/James_inthe_box/status/1039249889815801857 ```neutrino``` is also a dedicated malware family. Please, restore PR.

**Comment by stamparm** [comment]
1) Downloaded file (http://209.141.59[.]124/cc.exe) doesn't have any reference from AV industry to "neutrino" https://www.virustotal.com/#/file/63268eacff7ec3374bbacc621ec030d27782cbac639d59c1d1009a744745d5d7/detection
2) I can't find any reference to neutrino malware on Google

Neutrino is an EK

**Comment by stamparm** [comment]
https://malware.dontneedcoffee.com/2014/06/neutrino-bot-aka-kasidet.html

**Comment by stamparm** [comment]
https://malpedia.caad.fkie.fraunhofer.de/details/win.neutrino

p.s. please use the name "kasidet" as it will prevent mixup with neutrino EK

**Comment by MikhailKasimov** [comment]
OK

**Pull request closed without merging**
