### PR TITLE
Create heodo_stealer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Not sure about:

```
# Reference: https://twitter.com/500mk500/status/1221357493084921861

107.220.88.193:443
107.220.88.193:80
98.200.26.128:443
98.200.26.128:80
190.7.153.162:8085
107-220-88-193.lightspeed.dybhfl.sbcglobal.net
kklc.dvrlists.com
aplicaciones.coopsana.com.co
```

All look like DVR logins or similar

**Comment by MikhailKasimov** [comment]
Have cleaned this. If somewhat -- will revert them.

**Comment by stamparm** [comment]
https://malpedia.caad.fkie.fraunhofer.de/details/win.emotet

```
Emotet
aka: Geodo, Heodo 
```

**Comment by MikhailKasimov** [comment]
o_O That is unexpected... Because this variant has not-emotet signs to detect.

**Comment by stamparm** [comment]
Merging. Will keep an eye on it in future

**Pull request merged**
