### PR TITLE
Create darkcoders.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://twitter.com/ViriBack/status/1050543003935416321

### CODE REVIEW

**Comment by stamparm** [comment]
Just a login page. Discussed this kind of cases multiple times. C&C callbacks have value, login pages don't

**Comment by MikhailKasimov** [comment]
50/50. If someone from internal network connects to such login page, this can be considered as a semaphore of security incident. Personally, I'll appreciate such functionality.

**Comment by stamparm** [comment]
Possibility of a someone to get infected: very slim. Possibility of a someone to actually be a botnet operator (inside your network): zero to nil. Already discussed before

**Comment by MikhailKasimov** [comment]
Again, here is 50/50: it can be a operator from IT dep or IS dep. Nil -- possibly, but I wanna to have such detection although as ```suspicious``` one, even in case of being ```zero to nil```.

@stamparm  We can have a generic trail in ```suspicious``` folder, named, e.g., ```malicious_panel.txt```. And I'm insisting on it here.

**Pull request closed without merging**
