### PR TITLE
Update cobalt.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
`cobalt.txt` is for Cobalt Gang. Cobalt Strike is not Cobalt Gang

**Comment by MikhailKasimov** [comment]
> 
> 
> `cobalt.txt` is for Cobalt Gang. Cobalt Strike is not Cobalt Gang

I do not remember, which trail is responsible for Cobalt Strike... :( We have ```cobalt``` and ```apt_cobaltdickens```.

**Comment by stamparm** [comment]
There is only a feed `cobaltstrike.py`. There are no static trails for this as `Cobalt Strike` is not a malware - it is an attacking framework.

As I can see some interesting domains, you could create `cobaltstrike.txt` for this case

**Comment by MikhailKasimov** [comment]
> 
> 
> There is only a feed `cobaltstrike.py`. There are no static trails for this as `Cobalt Strike` is not a malware - it is an attacking framework.
> 
> As I can see some interesting domains, you could create `cobaltstrike.txt` for this case

Done in #1101

**Pull request closed without merging**
