### PR TITLE
Update domain.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Moving to ```dynamic_domain.txt``` list: https://github.com/stamparm/maltrail/pull/2247/commits/66564ca74c731899e94221020216782c58e80161

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
Just as an argument: ```Majority of these are from afraid.org. Please put them to dynamic_domain.txt``` (c) --> https://github.com/stamparm/maltrail/pull/1945#issuecomment-493759893

**Comment by stamparm** [comment]
To me, only those having reference `https://freedns.afraid.org/domain/registry/` seems truly ready to be placed into `dynamic_domains.txt`. Those other two references don't look to have many "dynamic" domain providers inside

**Comment by MikhailKasimov** [comment]
I was based on ```/dynamicdns/``` sign in link...

**Comment by MikhailKasimov** [comment]
Second link also is marked as dyn: ```# Reference: http://mirror1.malwaredomains.com/files/dynamic_dns.txt```

@stamparm  So, your decision?

**Comment by stamparm** [comment]
Please, only `afraid` ones to dynamic. Others can stay in `domain`. I am aware that it says "dynamic", though, authors have put all sorts of junk inside those two references

**Comment by MikhailKasimov** [comment]
OK, minute...

**Comment by MikhailKasimov** [comment]
@stamparm Fixed.

**Pull request merged**
