### PR TITLE
Update generic.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Fixing someone's ```...``` disrespective closing of entire trail instead of cutting off irrelevant records.

### CODE REVIEW

**Comment by stamparm** [comment]
`disrespective closing of entire trail instead of cutting off irrelevant records` <- but there was more than couple of thousands of trails??? I thought that it was far more easier for you to do it

**Comment by MikhailKasimov** [comment]
@stamparm Please, let's just cut off those snippets, that are irrelevant only. E.g: ```Mikhail, cut off the problematic records and then I'll merge other records you proposed for this trail```. -> this will save a lot of time for me not to re-parse and not to re-create records, which are good to be merged. Hence, such approach will save me a tone of nerves and time. Thanks!

**Comment by stamparm** [comment]
If you go back in history for thousands of merge requests you'll see that I don't do "disrespective" rejects. In this case I thought that it is easier for you to recreate two separate merge requests after I close this one. Recreation of records would be easy peasy with [commit history](https://github.com/stamparm/maltrail/pull/1894/commits)

**Comment by MikhailKasimov** [comment]
OK, sorry for being angry.

**Pull request merged**
