### PR TITLE
Enforce usage of urllib2 instead of urllib for updates

### PR DESCRIPTION
**Pull request by ptitdoc**
urllib1 SSL implementation is broken in some situations (for instance when using specific web proxies...).

### CODE REVIEW

**Comment by stamparm** [comment]
Can you please be more specific? In what kind of situations? Is there any reference for your claims? Also, SSL is broken in lots of situations for all Python libraries prior to 2.7.9/2.7.10

**Comment by ptitdoc** [comment]
I discovered this bug several month ago caused by a Fortnet web proxy (I searching for the reference I found at that time).

**Comment by ptitdoc** [comment]
https://docs.python.org/3.4/howto/urllib2.html:

> Currently urllib.request does not support fetching of https locations through a proxy. However, this can be enabled by extending urllib.request as shown in the recipe

**Comment by ptitdoc** [comment]
Here is another reference (maybe a better one):
https://chromiumcodereview.appspot.com/10825107/

**Pull request merged**
