### PR TITLE
Create apt_fin6.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
```http://``` prefix is used for case of ```80``` port.

### CODE REVIEW

**Comment by stamparm** [comment]
-> `fin6.txt`. Not an APT actor (`cyber crime group FIN6` from this [report](https://www2.fireeye.com/rs/848-DID-242/images/rpt-fin6.pdf))

**Comment by MikhailKasimov** [comment]
> -> fin6.txt. Not an APT actor (cyber crime group FIN6 according to this report)

I was based on ```apt_fin4.txt``` and ```apt_fin7.txt``` trails to have unified classification name. Still need to be renamed to ```fin6.txt```?

**Comment by stamparm** [comment]
You are right about those. Renamed them with the latest 52a849a

**Comment by MikhailKasimov** [comment]
```fin6.txt``` now.

**Pull request merged**
