### PR TITLE
Update dynamic_domain.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
`b3ta.org` is a domain parking site. Most probably some of those contacted domains just redirected (with `CNAME`) to that same service. Nothing to do with dynamic domain providing

**Comment by MikhailKasimov** [comment]
OK

**Comment by stamparm** [comment]
My mistake. `b3ta.org` is the parked one. Just seen the https://www.virustotal.com/#/domain/b3ta.org

**Comment by stamparm** [comment]
Please reopen so I could merge

**Comment by MikhailKasimov** [comment]
Resounded in #924

**Pull request closed without merging**
