### PR TITLE
Update zeus.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://pastebin.com/bPV4gVVL (pandabanker)

### CODE REVIEW

**Comment by stamparm** [comment]
Maybe to create a new `pandabanker.txt`?

**Comment by MikhailKasimov** [comment]
No. Panda (Trojan.PWS.Panda by Dr.Web) = Zbot = Zeus. Steals bank information.

And its config has the very close format (https://pastebin.com/67hhFaMZ) to its old versions (zeus v1 and v2. E.g.: https://www.virustotal.com/#/file/72be809dd0c9e0ad1eb4e13606cf3a0b45fb6bfa6204e151868e99a2fcbb87cb/detection).

**Comment by stamparm** [comment]
It is a new strain based on ZeuS:

https://www.proofpoint.com/us/threat-insight/post/panda-banker-new-banking-trojan-hits-the-market -> `Proofpoint researchers have been tracking a new banking Trojan with roots in Zeus. We have observed the malware, dubbed "Panda Banker", being used for targeted attacks via email attachments....Thanks to Fox IT InTELL , which discovered this malware in February and allowed us to properly name it in our signatures.`

**Comment by MikhailKasimov** [comment]
See also: https://twitter.com/JR0driguezB/status/1026849180835295232 (Panda, ZeusPanda). Even have no idea why just now Zeus became Panda in 2018, although this name was invented in 2007. That's true.

**Comment by stamparm** [comment]
Because it is a different malware based on ZeuS. Same as ZeuS Gameover or ZeuS VM (KINS)

**Comment by stamparm** [comment]
p.s. if https://www.proofpoint.com/us/threat-insight/post/panda-banker-new-banking-trojan-hits-the-market has a title `Panda Banker: New Banking Trojan Hits the Market` I am not sure what kind of argument is `Even have no idea why just now Zeus became Panda in 2018`

**Comment by MikhailKasimov** [comment]
``` I am not sure what kind of argument is Even have no idea why just now Zeus became Panda in 2018 ```

Voice from the history and my rather strong memory. :) And here is a question of unification, btw -- personally I'm against of generating pile of dedicated trails for what has the same root and can be detected by one single trail, which is already exist.

**Comment by stamparm** [comment]
Superseded by https://github.com/stamparm/maltrail/commit/705371afc9d47015de2b54f820e0ac58e23327cd

**Pull request closed without merging**
