### PR TITLE
Update phishing.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://www.virustotal.com/#/ip-address/85.17.26.65

```sort```-ed and ```uniq```-ed phishing domain-list.

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
Removed FP for yopi-car.com

**Comment by stamparm** [comment]
I said at least. Lots of domains from passive DNS lookup look like false-positives. Closing this down

**Comment by MikhailKasimov** [comment]
``` look like``` and other ```highly likely```-s... And closing with other real phishing domains like ```bcft.aero/ID/PayPal/Help/``` and later. You bet.

**Comment by MikhailKasimov** [comment]
E.g.:

``` facebox.aba.ae
faxebok.aba.ae```

look like false-positives, aha...

**Comment by MikhailKasimov** [comment]
I've rechecked these dimains on VT, I have doubts on ```zero.zz.com.ve``` and ```pdfdoc.aba.ae``` only. If you can see other clean stuff, please, give a hint. Thanks!

**Pull request closed without merging**
