### PR TITLE
Create kozbot.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This doesn't look like a new strain/malware from the VT report

**Comment by MikhailKasimov** [comment]
generic?

**Comment by stamparm** [comment]
I would say that it is one of those usual MSIL RAT suspects, but as we don't have any information, the `generic` should be the most appropriate

**Comment by MikhailKasimov** [comment]
Superseded by https://github.com/stamparm/maltrail/pull/11964/commits/19f1e170c13253af1a86e2f0d823a1e644f5c070

**Pull request closed without merging**
