### PR TITLE
Create clidak.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
-> `generic.txt`

**Comment by MikhailKasimov** [comment]
I would like to avoid ```generic```, because of ```/~pete19c/r.php``` is being rather specific. If you insist moving to ```generic```, OK.

**Comment by stamparm** [comment]
please into generic. `clidak` is a generic malware naming (it does not exists per se)

**Comment by MikhailKasimov** [comment]
Done in #9842 and #9843

**Pull request closed without merging**
