### PR TITLE
Create limeransom.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Where did `limeransom` come from? This looks like `AutoIt` installer/dropper

**Comment by MikhailKasimov** [comment]
> 
> 
> Where did `limeransom` come from? This looks like `AutoIt` installer/dropper

See VirusTotal reference link (e.g. Avira, F-Secure).

**Comment by stamparm** [comment]
This same sample is AutoIt (found wherever Google-ed - e.g. [here](https://alln-extcloud-storage.cisco.com/ciscoblogs/5c8293852fd07.txt)). Also, references like [urlhaus](https://urlhaus.abuse.ch/host/kuangdl.com/) suggest that this same domain is used for installation/downloading of various malware families. Please put to `generic.txt`.

**Comment by MikhailKasimov** [comment]
Closed on #882

**Pull request closed without merging**
