### PR TITLE
Update whitelist.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Cisco's FPs on https://blog.talosintelligence.com/2018/10/threat-roundup-0928-1005.html (Win.Malware.Gandcrab-6706045-0)

### CODE REVIEW

**Comment by stamparm** [comment]
There is no need for updating whitelist based on FP at some reference. Just not inclusion of FP into trails is enough. If you insist I'll do it, but in future, as said, there is no need for doing this

**Comment by MikhailKasimov** [comment]
Anyway, it is desirable to add these ones.

```but in future, as said, there is no need for doing this``` -- agreed. Thanks!

**Comment by MikhailKasimov** [comment]
M?

**Comment by stamparm** [comment]
Because of #627, dropping this down. If you insist, you can re-include some of those to the whitelist (as you did previously), but please drop the talosintelligence reference.

**Comment by MikhailKasimov** [comment]
```but please drop the talosintelligence reference.```

Looking into ```whitelist.txt```:

```# appeared on malwarepatrol.net```
```# appeared on malwaredomainlist.com```

So, how should I name such PR, if ``````but please drop the talosintelligence reference.```

P.S. On ```but please drop the talosintelligence reference.``` -- no problem. As I said above -- agreed.

**Pull request closed without merging**
