### PR TITLE
Create ISRStealer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://viriback.com/30-days-later-97-panels/

ISRStealer.

### CODE REVIEW

**Comment by stamparm** [comment]
`ISRStealer.txt` -> `isrstealer.txt`

**Comment by MikhailKasimov** [comment]
Renamed.

**Comment by stamparm** [comment]
going to make a different commit related to this one

**Comment by MikhailKasimov** [comment]
OK

**Pull request closed without merging**
