### PR TITLE
Update crypto_mining.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Page 10-11 of https://staging.nsfocusglobal.com/wp-content/uploads/2018/10/NuggetPhantom-Analysis-Report-V4.1.pdf

### CODE REVIEW

**Comment by stamparm** [comment]
isn't this malware?

**Comment by MikhailKasimov** [comment]
Generally --malware. But I have no idea what ```%{name}%_miner.txt``` is in game here. Faceless ```generic``` is not a variant here as for me.

**Comment by stamparm** [comment]
Only one simple question should be asked in this kind of situations: "is the trail related only to malware or it can be used for legitimate crypto mining purposes too (by legit software)"

**Comment by stamparm** [comment]
you can also use `unknown_miner.txt` (or `generic_miner.txt`) if `generic.txt` is not appropriate

**Comment by MikhailKasimov** [comment]
We can have new ```miner_generic.txt``` in ```/static/malware``` folder for such cases. Does this sound OK?

**Comment by MikhailKasimov** [comment]
Resounding in https://github.com/stamparm/maltrail/pull/13598

**Pull request closed without merging**
