### PR TITLE
Create cryptojack.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://twitter.com/bad_packets/status/1038705757552660480

### CODE REVIEW

**Comment by stamparm** [comment]
After a closer look I can see that this could go way beyond the "malware" story. I am against adding of mining JS scripts on compromised sites as those are not a good reference for "malware infection".

**Comment by MikhailKasimov** [comment]
50/50 here. This can give a hint to admin, that site compromised is and has a connection to some crypto-mining staff. Can be useful.

**Comment by stamparm** [comment]
https://docs.google.com/spreadsheets/d/1RdT_r4fi4wPx5rY306FftVKaXiAZeQeb5fx78DmbVx0/edit#gid=0

Based on that table somebody could blacklist (e.g.) Coinhive and say that it is a malicious service. I am not happy with that idea

**Comment by MikhailKasimov** [comment]
Here is again 50\50, just as a case with ```PUP``` : when someone uses crypto-mining on its own pc/laptop -- it's OK. When via someone else's ones -- it is evil and should be detected as a marker, that something is going wrong. Personally I'm OK to be alerted.

**Comment by stamparm** [comment]
`crypto_mining` should be to detect crypt mining voluntary (e.g. breaking of company's policy) or involuntary (e.g. malware).

Now, sporadic running of crypto JS (most probably involuntary) by visiting some compromised site or site which wants to generate some extra non-Ads revenue, will generate noise IMO.

**Comment by MikhailKasimov** [comment]
```(most probably involuntary)``` <-- that's the key phrase, IMHO. Personally, I have already two compromised sites to clean exactly from ```JS```-miners, which slow down sites, but hoster's tools are silent. And I'm looking for way to have simple beacon, which will give me a hint, that site has begun connections related to crypto-mining. And to block such connections on firewall. That's all. Noise? Possibly, but let us have some live tests to re-check this out and rate of such noise. M?

**Comment by MikhailKasimov** [comment]
BTW, addresses I put in PR here are not addresses of compromised sites, but sites, which these compromised sites try to connect to.

**Comment by MikhailKasimov** [comment]
https://twitter.com/bad_packets/status/1042630612853514240

**Comment by MikhailKasimov** [comment]
Resolved via ```malicious_js``` mechanism  ( #459 ).

```/lib/crypta.js``` , ```/bitrix/js/main/core/core_loader.js``` and ```/bitrix/js/main/core/core_tasker.js``` are here: https://github.com/stamparm/maltrail/pull/460/commits/67e0071f11e45ce7b53fd2412f01f25c05a8d3c2

**Pull request closed without merging**
