### PR TITLE
Update stealer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
"6te.net" - `About 821,000 results (0.33 seconds)`, `Creation Date: 2005-01-27T18:48:05Z`
"ftpupload.net" - Googling results with regular cases, but it seems to be used far too often for various "nefarious" purposes -> `malware/generic.txt`

**Comment by MikhailKasimov** [comment]
Do I understand it right, that ```"6te.net"``` goes to ```generic.txt``` too?

**Comment by stamparm** [comment]
6te.net - free web hosting provider

**Comment by MikhailKasimov** [comment]
generic + free_web_hosting (6te.net)

**Pull request closed without merging**
