### PR TITLE
Update ramnit.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://research.checkpoint.com/ramnits-network-proxy-servers/

Addressed from Figure 3.

### CODE REVIEW

**Comment by stamparm** [comment]
p.s. just noticed that those are already covered with https://github.com/stamparm/maltrail/blob/master/trails/feeds/bambenekconsultingc2dns.py, but nevertheless, nice to have it as static trails

**Comment by MikhailKasimov** [comment]
BTW, there are also strong feed-lists, as it was for 36.com DGA-feeds, to add to MT: http://osint.bambenekconsulting.com/feeds/  Please, consider!

**Comment by stamparm** [comment]
@MikhailKasimov out of all those, combined lists with "high confidence" are already being used ("High-Confidence C2 Domain Feed", "High-Confidence C2 IP Feed") along with "DGA Domain Feed". Hence, there is no need to add anything else (IMO)

**Comment by MikhailKasimov** [comment]
OK, thnx.

**Pull request merged**
