### PR TITLE
Update domain.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Majority of these are from `afraid.org`. Please put them to `dynamic_domain.txt`

**Comment by MikhailKasimov** [comment]
> 
> 
> Majority of these are from `afraid.org`. Please put them to `dynamic_domain.txt`

Done: #1957

**Comment by stamparm** [comment]
`k.vu` is also afraid.org. At the page itself: `DNS for this domain is provided by FreeDNS. Report abuse on k.vu subdomains to dnsadmin@afraid.org.`

**Comment by MikhailKasimov** [comment]
Oops... Moved to #1961

**Pull request closed without merging**
