### PR TITLE
Update dynamic_domain.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Many of these domains simultaneously live in ```domain``` and ```dynamic_domain``` lists. Wanna do deduplication by moving them into one single place -- ```dynamic_domain```.

### CODE REVIEW

**Comment by stamparm** [comment]
But lots of these are not "dynamic" as compared to our existing entries, even though the reference says: `http://trojanedbinaries.com/security/dynamicdns`

Dynamic domains should have its own provider gaining "dynamic DNS" service to anybody (registered)

**Comment by stamparm** [comment]
I would either leave it as is or remove the entries from http://trojanedbinaries.com/security/dynamicdns altogether from `domain.txt` because of lots of junk inside

**Comment by MikhailKasimov** [comment]
OK, I propose to leave junks in ```domain``` and move all other ones to ```dynamic```.

**Comment by stamparm** [comment]
In such case I would leave everything as is

**Comment by MikhailKasimov** [comment]
OK, gonna close these two PRs.

**Pull request closed without merging**
