### PR TITLE
Update js_script.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Not sure about these. It looks like regular pharma scam/spam

**Comment by MikhailKasimov** [comment]
Generally. But, they compromise legit site to make redirection to their scam: https://twitter.com/unmaskparasites/status/1321506413995159552 That's the reason I put these domains into ```js_script```.

**Comment by stamparm** [comment]
There are tons of similar redirect scams on compromised sites all over the web. Redirection itself is just a "blackhat seo" tactic, while JS does not have any intelligent logic inside

**Comment by MikhailKasimov** [comment]
OK. Then I have cleaned trail: https://github.com/stamparm/maltrail/pull/11888/commits/0d93108cb56da9e3e64eecfee75ac07b62f47c9b

**Pull request merged**
