### PR TITLE
Update luminositylinkrat.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Ok about domains, but IPs are from 2015-2016. Please only domains

**Comment by MikhailKasimov** [comment]
IPs have thier specific ports. In case of 80, 443 -- OK, but when specific ports are met, standing to save the detection.

**Comment by stamparm** [comment]
3 years old IOCs that are not domain names are unusable at least (I don't want to use other wording)

**Comment by MikhailKasimov** [comment]
@stamparm https://github.com/stamparm/maltrail/pull/2508/commits/533090edd4be8e426a927da42bbed4d5e76764f2

**Pull request merged**
