### PR TITLE
Update generic.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
`dnsip.ru` and `dns-free.com` look like `suspicious/dynamic_domain.txt`

**Comment by stamparm** [comment]
Even on https://doc.emergingthreats.net/bin/view/Main/2022378 `dnsip.ru` is marked as `ET INFO DYNAMIC_DNS`

**Comment by stamparm** [comment]
p.s. now doing own analysis to make sure what's going on

**Comment by MikhailKasimov** [comment]
> dnsip.ru and dns-free.com look like suspicious/dynamic_domain.txt

Just ```look like```. Well, personally no problem to move them, but from this domain malicious client can be downloaded (see first ```# Reference``` link). Hence I put them to ```generic``` trail.


Let's decide -- ```generic``` (of spreading malware directly) or ```dynamic_dns```?

**Pull request merged**
