### PR TITLE
Create huntpos.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://twitter.com/ViriBack/status/1046877151599976448

IP is alive.

### CODE REVIEW

**Comment by stamparm** [comment]
This is admin panel. Most probably the `/gate.php` is the malware callback

**Comment by MikhailKasimov** [comment]
```/gate.php``` returns 404. Here is to detect IP, while it is alive, or connection to ```/admin.php```. But detection should be present.

**Comment by stamparm** [comment]
I like you and all but I don't have time for this kind of nonsense here and there. I double check what I write. Haven't it occurred to you that the 404 might be fake? You tend to introduce me into this kind of ping-pong messaging and I dislike it.

screen

**Comment by MikhailKasimov** [comment]
```Out-of-deal section:``` Easy on tone, please. I also have much of my basic work and adding trails can be done among other many tasks I have. And one of them -- to support MT on servers, where I work, to keep user's support and so on. And something I can really miss among all of this stuff. And I can't see crowd of contributors with tones of PRs with malware detection updates. Probably, you do. If you do not appreciate external help -- OK, it's your deal. But, please, with easy on tone. Thank you.

```Deal section:```

Does list 
```
185.219.221.73/config.php
185.219.221.73/dumpAction.php
185.219.221.73/gate.php
185.219.221.73/install.php
```
OK to be added?

**Comment by stamparm** [comment]
I am quite easy on tone - compared to some other situations on other projects. I don't like ping-pong messaging when stuff looks quite clear (at least from my perspective). I appreciate your help, but when I get lousy arguments (like those on Panda Banker - which I "fixed" by just including new `pandabanker.txt` trail) or non-checked sources inside the pull-requests I have a bad feeling where I have to react somehow to make it more "professional".

**Comment by stamparm** [comment]
I appreciate your work. Though, this is an free and open-source project where nobody makes money nor fame and I am the [BOFH](https://en.wikipedia.org/wiki/Bastard_Operator_From_Hell). C'est la vie

**Comment by MikhailKasimov** [comment]
OK, peace. I also do not like ping-pong, especially, when deal is clear.

About ```lousy arguments (like those on Panda Banker)``` : see ```elf_torii.txt``` trail, when new malware-family is not "child" of root-form (Mirai). I'm OK on something new, but when it is not redundant.

``` non-checked sources inside the pull-requests I have a bad feeling where I have to react somehow to make it more "professional" ```

And you are right on here. But when I met some list on external resource, I believe, its creators have checked links they add. And when clean links are present (on your checks), that's make me really angry. Because this makes double empty work from your side and my side. At the same time I really thankful, when you point, where am I missed something.

```C'est la vie``` -- certainly.

So, peace again and let us keep on our work to make MT perfectly good on malware detection!

**Comment by MikhailKasimov** [comment]
Again:

Does list

```
185.219.221.73/config.php
185.219.221.73/dumpAction.php
185.219.221.73/gate.php
185.219.221.73/install.php
```
OK to be added as s trail?

**Comment by stamparm** [comment]
@MikhailKasimov you can add it

**Pull request closed without merging**
