### PR TITLE
Update njrat.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
1) Referenced VT reports contain only one IP:port connection
2) Generating "past" IP:ports based on previous IPs used for domain, while in the same time malware EXPLICITLY uses domains for connection, doesn't make any sense. This is related to one of our previous discussions where I said that IP:port in presence of domain is practically worthless

**Comment by MikhailKasimov** [comment]
1. E.g. # Reference: https://www.virustotal.com/gui/file/9dd248ea5246bb7aa9b5c8a101166750e1bfd71c575bf58037ed147764f12f43/detection --> ```mammoth01.ddns.net``` is already present, so all ```IP:port``` were added for guaranteed covering all samples from ```Communicating Files``` section.

2. ```doesn't make any sense``` <-- ``` Sometimes I put IP:port, sometimes not. We are not doing a science here :) ... As said, if there is a domain related to the malware, that's valuable IOC. If you put IP:port, great. I also put it in lots of cases. Just don't take it seriously if I don't do it every time``` (c) MS. It is from our discussion. And as said **always** I put IP:port to cover cases, when DNS is not in use by malware, just IP:port.

P.S. Also, all other trail (nanocore, xtrat, etc) with the same generalization on "past" ```IP:port+DNS``` got merged today, but not njrat... Weird...

**Comment by stamparm** [comment]
`Also, all other trail (nanocore, xtrat, etc) with the same generalization on "past" IP:port+DNS got merged today, but not njrat... Weird...`

Well, things like this sticks into an eye:

```
103.212.180.234:1177
147.50.241.204:1177
182.232.217.172:1177
182.232.217.182:1177
182.232.217.194:1177
182.232.225.43:1177
182.232.228.46:1177
182.232.46.30:1177
223.205.80.236:1177
223.205.82.15:1177
223.205.82.192:1177
223.205.82.213:1177
223.205.83.13:1177
223.205.86.102:1177
223.205.86.13:1177
223.205.86.146:1177
223.205.87.7:1177
223.206.144.116:1177
223.206.144.152:1177
223.206.144.41:1177
223.206.144.9:1177
223.206.145.243:1177
223.206.145.82:1177
223.206.146.120:1177
223.206.146.15:1177
223.206.147.149:1177
223.206.148.100:1177
223.206.148.194:1177
223.206.149.109:1177
223.206.151.150:1177
223.206.151.156:1177
223.206.151.33:1177
223.206.64.227:1177
223.206.65.2:1177
223.206.65.33:1177
223.206.66.199:1177
223.206.67.132:1177
223.206.67.230:1177
223.206.67.245:1177
223.206.68.104:1177
223.206.70.166:1177
223.206.70.198:1177
223.206.71.133:1177
223.206.71.28:1177
43.229.151.248:1177
77.78.103.20:1177
94.229.67.133:1177
```

This is called "extrapolation" (i.e. over-stretching) of data based on passive DNS records for `mammoth01.ddns.net` (you've done based on https://www.virustotal.com/gui/domain/mammoth01.ddns.net/relations)

Why is this bad. For example, `77.78.103.20` was used in 2019-12-12, while there were dozens of other IP addresses appearing afterwards. Malware is EXCLUSIVELY using dynamic domain address for communication, which seems to be regularly UPDATED. 

Putting whole 0.0.0.0:1177 doesn't make any sense.

**Comment by stamparm** [comment]
Extrapolating of couple of IPs would go under the radar, but extrapolating more than 20 IPs per one dynamic domain obviously won't :)

**Comment by MikhailKasimov** [comment]
The problem is if port 80 or even 443 is in use -- OK, but not when 1177, 5552 (the most used port for njrat). And it's not someone's fault, when ```mammoth01.ddns.net``` resolves > 20 IP : they are anyway belong to malware. Certainly, all of them would covered by ```mammoth01.ddns.net```, but... I try to cover samples in all accessible ways, especially when amount of such samples > 10.

**Pull request merged**
