### PR TITLE
Update android_roamingmantis.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
To avoid potential detection in the middle of some strings/domains/etc.

### CODE REVIEW

**Comment by stamparm** [comment]
https://github.com/stamparm/maltrail/pull/2763#issuecomment-510829734

**Comment by MikhailKasimov** [comment]
@stamparm Fixed

**Comment by stamparm** [comment]
@MikhailKasimov p.s. just be aware that `^` will skip cases like `www.<malicious_domain`. So, use it wisely

**Comment by MikhailKasimov** [comment]
> 
> 
> @MikhailKasimov p.s. just be aware that `^` will skip cases like `www.<malicious_domain`. So, use it wisely

Yeah, I already thought on it when adding today's regex for phishing. On ```roamingmantis``` there are no domains with ```www.```.

**Pull request merged**
