### PR TITLE
Create empire.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
`generic.txt`

**Comment by MikhailKasimov** [comment]
Idea is the same to ```/malicious/covenant.txt```. When merged, Wiki-page "Specific detections" also gonna be updated.

**Comment by stamparm** [comment]
But what is "Empire" in this case?

**Comment by stamparm** [comment]
If it is Powershell Empire, then it is strange to have only one trail for something that is for years around

**Comment by MikhailKasimov** [comment]
> If it is Powershell Empire,

Looks, it is https://github.com/BC-SECURITY/Empire in fact.

>  then it is strange to have only one trail for something that is for years around

We started to track ```/malicious/covenant.txt``` also with few of trails only...

**Pull request closed without merging**
