### PR TITLE
Create malicious_php.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://www.virustotal.com/#/ip-address/85.17.26.65 (#URL section)

The idea is similar to ```malicious_js.txt``` trail and is a some rethought of #313 -- to detect suspicious ```.php```.

### CODE REVIEW

**Comment by stamparm** [comment]
I believe that you are over-reaching now. It is great that you want to cover lots of stuff, but there is no need to cover everything. You'll burn out.

Malicious PHP can have any arbitrary name. As I've seen, if not strictly malware related (e.g. like `/gate.php`), bad guys choose really fascinating names. If not malware related (i.e. they can't be related to some malware strain) I would not do this kind of stuff

**Comment by MikhailKasimov** [comment]
Well, I took that ones, that are related to malware or phishing only. Otherwise, I would put ```index.php```, ```login.php``` and so on. :) And in this case yes, that will cover huge pile of clean resources. That's why I try to put other parts of path (e.g.: ```/1/``` , ```/r/``` and other sign combinations), to make detection more specific instead of wide.

**Comment by MikhailKasimov** [comment]
So?

**Comment by MikhailKasimov** [comment]
@stamparm Thanks!

**Pull request merged**
