### PR TITLE
Update php_script.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Related to https://github.com/stamparm/maltrail/pull/9996

### CODE REVIEW

**Comment by stamparm** [comment]
Malware specific PHP callbacks should go to `malware` trails

**Comment by MikhailKasimov** [comment]
The deal is that this ```malware``` has no valid name.

**Comment by stamparm** [comment]
e.g. `/gateinfo` and `/gatedrives` seem to me like (only) `exorcist` related

**Comment by MikhailKasimov** [comment]
OK, gonna move this.

**Comment by MikhailKasimov** [comment]
Done in https://github.com/stamparm/maltrail/pull/10020

**Pull request merged**
