### PR TITLE
Create gtbot.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
You just copy-pasted everything from `https://www.virustotal.com/#/domain/afraid.org`. For example, `topmail.afraid.org` doesn't have anything to do with GBot. Also, `banned-for-abuse.afraid.org` is a valid CNAME used by `afraid.org` (to mark reported domains), not having anything to do with the GBot

**Comment by stamparm** [comment]
Proper example would be:

```
Reference: https://www.virustotal.com/#/file/bc5662f91493da2bd02781832f8728a3eba350e47ed11cd8f927e3cb88a44452/behavior

thepriest.no-ip.org
divxrulz.myftp.org
polarbbs.mine.nu
ityoill1goto.YGTO.com
host1liil1.mooo.com
1liil11liil1.afraid.org
till1liil1.afraid.org
thisisliil1.b3ta.org
imiill11lnot.afraid.org
user1l1l.a-p-e.m-a-f-i-a.com
l.1ove.you.oil1y.afraid.org
il1l.d0.l.hear.a1l.mooo.com
hlph0pfIipf10p.afraid.org
1l2lI.0n.my.ignorelist.com
ftp.binary01O100lI.YGTO.com
l1l1Il1I.y20O3zuxx.xxuz.com
```

**Comment by MikhailKasimov** [comment]
@stamparm What to do with ```YGTO.com```? It is dead, but is also absent in ```dynamic_domain``` trail. I could add.

**Comment by stamparm** [comment]
@MikhailKasimov put a reference to https://www.virustotal.com/#/domain/ygto.com and use `ygto.com`

**Pull request closed without merging**
