### PR TITLE
Create elf_btcminer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://www.virustotal.com/en/file/0687cd8d38c334a970b81b1ba9bb2e18aa66424edba3f33b61f7d03e35d5db20/analysis/

Other names were taken from sh-loaders, which usually contain ```pkill -f``` list to kill processes of other (concurrent) ELF-miners. Certainly, minus names like ```wget``` and so on.

### CODE REVIEW

**Comment by stamparm** [comment]
These are file paths. Maltrail is network layer monitor. Closing this down

**Comment by MikhailKasimov** [comment]
Facepalm... @stamparm Please, stop being such inadequate. :( We use paths like ```/XBash``` for ```elf_xbash.txt``` trail and so on.

These all are NOT filesystem trails, but **network** instead. Generic **network** trails.

**Comment by MikhailKasimov** [comment]
Another example: https://www.codeblogbt.com/archives/145523

``` ...where the short link is restored to https://xmr.enjoytopic.tk/.12/r88.sh. If it is not a root account, the planned task is not written. Next, a series of operations are downloaded to run rootv2.sh or lowerv2.sh, which is based on whether the current account is root or not. ```

**Comment by MikhailKasimov** [comment]
https://www.reverse.it/sample/0c5e960ca2a37cf383a7457bcc82e66d5b94164b12dfca1f21501211d9aca3c9?environmentId=300

```

Endpoint | Request | URL | Data
-- | -- | -- | --
45.77.106.29:80 | GET | /rootv2.sh | GET /rootv2.sh HTTP/1.1 Host: 45.77.106.29 User-Agent: curl/7.47.0 Accept: */*  200 OK

```

@stamparm Is it enough for you to begin to see **network** ?

**Comment by MikhailKasimov** [comment]
@stamparm https://www.alibabacloud.com/blog/jbossminer-mining-malware-analysis_593804

https://blog.talosintelligence.com/2018/08/rocke-champion-of-monero-miners.html

**Pull request closed without merging**
