### PR TITLE
Create elf_hacked_exim.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
Maybe `elf_generic` ? There will be lots of hacked binaries around. If there is no proper malware name, generic one should be a better choice

**Comment by MikhailKasimov** [comment]
From https://habr.com/ru/company/first/blog/455636/ (```Залил туда же исходник скрипта малвари, который удалось вытащить с зараженного сервера.``` --> ```Have uploaded source of malware-script, which was got from infected server```). That's why I put to explicitly-named trail.

**Comment by MikhailKasimov** [comment]
UPD:

From https://habr.com/ru/post/455598/#comment_20266864

```Обнаружил у себя другую разновидность зловреда. В очереди exim сидело вот такое:
46h 750 1hZzGN-0006uF-Th <> *** frozen ***
...


Скачивает и выполняет скрипт с http://173.212.214.137/s
Судя по коду, собирает различные данные с системы, пакует в архив и отправляет куда-то.```

->

```Have discovered another variation of malware. Exim's queue had:
46h 750 1hZzGN-0006uF-Th <> *** frozen ***
...

Downloads and runs script from http://173.212.214.137/s
Dueto its code, collects various of system data, packs to archive and sends somewhere.```

As you can see ```173.212.214.137```  is in #2298

**Comment by MikhailKasimov** [comment]
@stamparm ?

**Comment by MikhailKasimov** [comment]
Close on moving to ```elf_generic.txt```: https://github.com/stamparm/maltrail/pull/2333/commits/48a810104bbfbc193a79a629f2c1203d9c3f6b98

Reason: https://twitter.com/bad_packets/status/1140719767961001984 (another vulnerability is in use with the same C2 address).

**Pull request closed without merging**
