### PR TITLE
Update qakbot.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This doesn't look good. It seems like a decoy traffic to me to hide a real C&C

**Comment by stamparm** [comment]
One of related samples (https://www.virustotal.com/gui/file/d6cda4b65efa7136a6c269f681196aa63935c93d959dbb9bdf338ba6ed69b5d6/behavior/QiAnXin%20RedDrip) is called `TheUntraceable RAT.exe`. Anyway, author(s) is trying to mask the real C&C(s) behind all this junk traffic

**Comment by MikhailKasimov** [comment]
OK, can be closed. Will add ```ip-adress.com``` to ```ipinfo.txt``` trail -- we do not have this one.

**Comment by stamparm** [comment]
Anyway, as I see that sample(s) are not doing a random generation of those IP:port combinations, I would reduce the "junk"/"noise" to contain only the non-80 and non-443 combinations. That way it would be reduced to something meaningful

**Comment by stamparm** [comment]
`ip-adress.com` is an interesting thing that I've also learned from this example :). It seems that author(s) are trying to do an "interesting" evasion with this one. I could do some generic stuff, like we do for the `onion` trails

**Comment by MikhailKasimov** [comment]
> Anyway, as I see that sample(s) are not doing a random generation of those IP:port combinations, I would reduce the "junk"/"noise" to contain only the non-80 and non-443 combinations. That way it would be reduced to something meaningful

OK, I currently do not delete this branch.

**Comment by MikhailKasimov** [comment]
> `ip-adress.com` is an interesting thing that I've also learned from this example :). It seems that author(s) are trying to do an "interesting" evasion with this one. I could do some generic stuff, like we do for the `onion` trails

#8018 (ipinfo)

```I could do some generic stuff, like we do for the `onion` trails``` -->OK. Thnx!

**Comment by MikhailKasimov** [comment]
Just to be linked: https://github.com/stamparm/maltrail/commit/0e4736648c1876c3fd0ce6a28d19c98c9b354715

**Pull request merged**
