### PR TITLE
Create atilla.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This domain doesn't look like C&C. Even in referenced sample contacted domain is different

**Comment by MikhailKasimov** [comment]
I decided to put this as ```malware``` instead of ```malicious_service``` or ```malicious_forum```, because of promoting one only malware by ```atilla.vip```.

**Comment by stamparm** [comment]
Frankly, I don't see a difference of this and `lofi.stream` inside `malicious_service`. Also, if visitor goes to `atilla.vip` that can't be marked the same as a regular malware contacting C&C

**Comment by MikhailKasimov** [comment]
OK, will move this to ```_service.txt```

**Comment by stamparm** [comment]
`961api.com` to me looks like a valid "licensing" platform, most probably used by "atilla". Not a C&C

**Comment by MikhailKasimov** [comment]
OK, let's close this on this moment. Will create another instance, if something new is in public about this trojan.

**Pull request closed without merging**
