### PR TITLE
Create jscoffe.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
[0] https://www.symantec.com/security-center/writeup/2018-092007-1208-99

It is not ```suspicious```, but ```malware``` instead case.

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
@stamparm acceptable here?

**Comment by MikhailKasimov** [comment]
So?

**Comment by stamparm** [comment]
`Infostealer.Jscoffe is a malicious script embedded on ecommerce websites to steal users' credit card information at checkout` <- not malware

**Comment by MikhailKasimov** [comment]
Infostealer <- not malware? o_O

**Comment by stamparm** [comment]
Let me repeat: `Infostealer.Jscoffe is a malicious script embedded on ecommerce websites to steal users' credit card information at checkout`. Please, don't pull me into the unnecessary discussion. You have the `malicious_js` for this kind of stuff.

**Comment by MikhailKasimov** [comment]
``` You have the malicious_js for this kind of stuff.``` <-- that is just exactly, what I was expecting to hear from you without pulling you ```into the unnecessary discussion```. ;) Thanks, will remove.

**Comment by stamparm** [comment]
Those that are left just hosts that are serving those malicious JS. Please put them too into the `malicious_js.txt`.

**Comment by MikhailKasimov** [comment]
Finally superseded by #521

**Pull request closed without merging**
