### PR TITLE
Create ghost419.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
```Ghost419 is based on Gold Dragon and Brave Prince implants and contains shared elements and code, especially for system reconnaissance functions.```

### CODE REVIEW

**Comment by stamparm** [comment]
-> `apt_unclassified.txt`. AFAIK, those are tool/malware names used by unknown actors

**Comment by MikhailKasimov** [comment]
Mmmm... I'm standing for some duplication: 1) we have malware-named trail + 2) apt, where this malware took is/was a participant. So, ```ghost419.txt``` + ```apt_unclassified.txt```. M?

**Comment by stamparm** [comment]
Golden rule should be: if malware is used ONLY in case of APT attacks by particular group, then preferred way should be to put it in `apt_XYZ` trail. In all other cases there could be two trail files.

Just ask a question to yourself. If `foobar.com` domain is being found inside the DNS traffic, should user be warned of APT group of malware name. I believe that APT group should have a precedence as it seems more important in matter of things

**Comment by MikhailKasimov** [comment]
OK, one minute...

**Comment by MikhailKasimov** [comment]
Resounded in https://github.com/stamparm/maltrail/pull/2265

**Pull request closed without merging**
