### PR TITLE
Update bad_service.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
There are tons of "hacking forums". We are not going to blacklist them one by one

**Comment by MikhailKasimov** [comment]
Currently this one appears, when you try to connect to C2 from ```denizkizi.txt```. I missed to cross-link two trails in description, sorry. :(

**Comment by stamparm** [comment]
But, this is a regular (hacking) forum

**Comment by MikhailKasimov** [comment]
OK.

**Pull request closed without merging**
