### PR TITLE
Update crypto_mining.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This is more a `malware` stuff than `suspicious`. Also, `crypto_mining.txt` should contain only general crypto-mining pools, while this seems to be a case-specific

**Comment by MikhailKasimov** [comment]
OK, where to move?

**Comment by MikhailKasimov** [comment]
Closed via #6690

**Comment by stamparm** [comment]
As per https://www.cybereason.com/hubfs/BitBucket%20Malware%20Arsenal%20IOCs.pdf, this is a mish-mesh of different malware. Also, those VT references don't have a specific (non-generic) name. Maybe just to put it into the `generic.txt`?

**Comment by MikhailKasimov** [comment]
I initially sorted this ```bucket``` to keep ```azorult``` and others to their own trails. This one is unknown and, while port 7777 is specific, I decided to put Kaspersky's|NOD32's detection name. Let it live in dedicated trail. If somewhat -- will move or merge with others.

**Pull request closed without merging**
