### PR TITLE
Create cobaltstrike.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
@stamparm Mergable or need some fixes?

**Comment by stamparm** [comment]
After a second look, report after all says `2018-10-22: Ukrainian telcos fake domains on servers with Metasploit and Cobalt Strike`. Sorry, for ping-ponging, but this should go into `generic.txt` (no better alternative this moment)

**Comment by MikhailKasimov** [comment]
> 
> 
> After a second look, report after all says `2018-10-22: Ukrainian telcos fake domains on servers with Metasploit and Cobalt Strike`. Sorry, for ping-ponging, but this should go into `generic.txt` (no better alternative this moment)

Hm... OK. I'll put ```185.25.50.168:4444``` and ```89.105.202.62:1080``` into ```cobalt.txt``` and domains to ```generic.txt```

**Comment by MikhailKasimov** [comment]
Closen via #1121 and #1122

**Pull request closed without merging**
