### PR TITLE
Create android_krbot.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
krbot?

**Comment by MikhailKasimov** [comment]
As I can see, there are Android samples only...

**Comment by stamparm** [comment]
But I can't find any report on it. VT is not the best choice for picking a name

**Comment by MikhailKasimov** [comment]
Yes, just https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=TrojanSpy:AndroidOS/Krbot!rfn&ThreatID=2147760261 . But also these samples are also similar to ```android_spynote``` behaviour: connection to dyn-domain with specific port. In this case I would like to avoid giving ```android_generic```. So, let's decide what name to put here.

**Comment by stamparm** [comment]
We are playing naming here. Generic is always the best place for this "new" and "unknown" samples. Later on they can be easily switched to another file once they come up in some other report

**Comment by MikhailKasimov** [comment]
Ok, reverting. In https://github.com/stamparm/maltrail/pull/10709

**Pull request closed without merging**
