### PR TITLE
Create android_flubot.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This list will need some cleanup (e.g. ` imwedsonpassos.com.br`)

**Comment by stamparm** [comment]
lots of FPs here:

```
cloudstrading.com
colegioaugustoribeiro.com.br
creolegarden.com
dilalla.com.ar
raku-plus.com
ryansa.com
sprintintercom.com.au
...
```

**Comment by stamparm** [comment]
I would really remove all those non-DGA looking sites

**Comment by MikhailKasimov** [comment]
> I would really remove all those non-DGA looking sites

+1. That's all were distribtion domains: mixing compromised sites and so on. Fixed.

**Comment by stamparm** [comment]
thx :D

**Pull request merged**
