### PR TITLE
Create elf_pua.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Related to https://github.com/stamparm/maltrail/pull/12104

### CODE REVIEW

**Comment by stamparm** [comment]
why split to elf_coinminer and elf_pua in this case?

**Comment by MikhailKasimov** [comment]
Because this sample is not coinminer itself and potentially can be used with other malwares.

**Comment by stamparm** [comment]
`elf_generic`

**Comment by MikhailKasimov** [comment]
Superseded by https://github.com/stamparm/maltrail/pull/12125/commits/3cc63c432da6de5f886a7c14e79e685abfcf458f

**Pull request closed without merging**
