### PR TITLE
Create socelars.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**

### CODE REVIEW

**Comment by stamparm** [comment]
This is some generic stuff

**Comment by stamparm** [comment]
Identical Issue one month ago:  #8546

**Comment by MikhailKasimov** [comment]
Oh, thanks! I felt it already was somewhere, but couldn't find it. Will remove.

**Comment by MikhailKasimov** [comment]
Moved: https://github.com/stamparm/maltrail/pull/9194

**Pull request closed without merging**
