### PR TITLE
Update apt_chafer.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
See ```Control server HTTP URL``` in ```Configuration``` table.

### CODE REVIEW

**Comment by stamparm** [comment]
You know that I am not a fan of IP trails. This one is from 2018, hence, nobody would miss it if not merged

**Comment by MikhailKasimov** [comment]
Just as historical one.

**Comment by stamparm** [comment]
WHOIS for that same IP is `Choopa, LLC` (VPS provider). It most probably changed couple of owners till now. I had problems with this kind of "trails" when CDNs don't care about the reputation of IPs (buying whatever they can for least possible price)

**Comment by MikhailKasimov** [comment]
OK.

**Pull request closed without merging**
