### PR TITLE
Add web hosting providers associated with malware

### PR DESCRIPTION
**Pull request by wesinator**
ftp.totallyanonymous.com 
drivehq.com

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
On ```drivehq.com```: https://github.com/stamparm/maltrail/commit/c98f964d0930952cfd3db0949edb7d6fc292d512#diff-e5f30826d13a8bd447554e2b74fadd26

**Comment by stamparm** [comment]
1) `drivehq.com` is legit service. Google says so. Can't blacklist the whole domain
2) https://www.scumware.org/report/drivehq.com - last report regarding that domain is for 2018

**Comment by stamparm** [comment]
@wesinator - sorry, now i see that the trail was going into free_web_hosting. Will merge

**Comment by wesinator** [comment]
Thanks, for what it's worth, there is also more recent reports on https://www.scumware.org/report/www.drivehq.com

**Pull request merged**
