### PR TITLE
Update emotet.txt

### PR DESCRIPTION
**Pull request by MikhailKasimov**
sorted-uniqed list of emotet c2s.

### CODE REVIEW

**Comment by stamparm** [comment]
I can merge this, but:

1) You know that I am not a huge fan of IP based trails (especially for malware)
2) Emotet changes C2 IPs like shoes

**Comment by MikhailKasimov** [comment]
1) Yes, I remember it, but can not see any reliable way to detect it just because exactly of 2). :(

**Comment by stamparm** [comment]
If you are willing to update it regularly (e.g. once a month), while removing the old ones (e.g. just replace previous list with the current) I am willing to merge it.

**Comment by MikhailKasimov** [comment]
Will try to track  info of dead emotet's c2s and to clean this list.

**Pull request merged**
