### PR TITLE
Installation guide for different Linux distros

### PR DESCRIPTION
**Pull request by MikhailKasimov**
Installation description update for different Linux distros (Debian/Ubuntu and SUSE/openSUSE).

### CODE REVIEW

**Comment by stamparm** [comment]
```
sudo zypper install gcc gcc-c++ git libpcap-devel python2-pip python-devel python3-devel
sudo pip2 install pcapy
git clone https://github.com/stamparm/maltrail.git
cd maltrail
sudo python sensor.py
```

1) Why installing both python2 and python3 devel packages?
2) There is no need for explicit Python2 environment, thus, if there is a way to just choose default python packages (like in case of Debian/Ubuntu), that would be the best

**Comment by MikhailKasimov** [comment]
Because I have\use openSUSE, and these packages were needed to have normally working MT sensor.

**Comment by stamparm** [comment]
Both Python2 and Python3 `devel` packages?

**Comment by MikhailKasimov** [comment]
Yes.

**Pull request merged**
